FROM odoo:latest

# Install dependencies (if needed)
# RUN apt-get update && apt-get install -y <package_name>

# Copy any custom setup scripts or entrypoint adjustments here if needed

# Example if you need to customize the odoo.conf directly:
# COPY ./config/odoo.conf /etc/odoo/odoo.conf

# Expose the Odoo port
EXPOSE 8069